C = [
(1,"Runway","Dot","R U2 R2 F R F' U2 R' F R F'","Dot with two opposite corners pointing out; looks like a runway."),
(2,"Zamboni","Dot","F R U R' U' F' f R U R' U' f'","Dot; two OLL-45 shapes stacked."),
(3,"Anti-Mounted Dot","Dot","f R U R' U' f' U' F R U R' U' F'","Dot with a bar on the back-right."),
(4,"Mounted Dot","Dot","f R U R' U' f' U F R U R' U' F'","Dot with a bar on the back-left."),
(5,"Wario","Square","r' U2 R U R' U r","Square shape in the bottom-left corner."),
(6,"Mario","Square","r U2 R' U' R U' r'","Square shape in the bottom-right corner."),
(7,"Lightning","Small Lightning","r U R' U R U2 r'","Small lightning bolt pointing up-right."),
(8,"Reverse Lightning","Small Lightning","r' U' R U' R' U2 r","Small lightning bolt pointing up-left."),
(9,"Kite","Fish","R U R' U' R' F R2 U R' U' F'","Fish shape; headlights on the left."),
(10,"Anti-Kite","Fish","R U R' U R' F R F' R U2 R'","Fish shape; headlights on the right."),
(11,"Downstairs","Small Lightning","r U R' U R' F R F' R U2 r'","Lightning with a bar on the left."),
(12,"Upstairs","Small Lightning","M' R' U' R U' R' U2 R U' R r'","Lightning with a bar on the right."),
(13,"Gun","Knight Move","F U R U' R2 F' R U R U' R'","Knight-move shape; looks like a gun."),
(14,"Anti-Gun","Knight Move","R' F R U R' F' R F U' F'","Mirror of the gun shape."),
(15,"Squeegee","Knight Move","r' U' r R' U' R U r' U r","Knight move with a bar on the left."),
(16,"Anti-Squeegee","Knight Move","r U r' R U R' U' r U' r'","Knight move with a bar on the right."),
(17,"Diagonal","Dot","R U R' U R' F R F' U2 R' F R F'","Dot with two diagonally opposite corners."),
(18,"Crown","Dot","r U R' U R U2 r2 U' R U' R' U2 r","Dot with a bar across the back."),
(19,"Bunny","Dot","r' R U R U R' U' M' R' F R F'","Dot with corners pointing to the sides."),
(20,"Checkers","Dot","r U R' U' M2 U R U' R' U' M'","Dot with all four corners twisted; checkerboard."),
(21,"Double Sune","Cross","R U2 R' U' R U R' U' R U' R'","Cross; all four corners misoriented, headlights all round."),
(22,"Double Antisune","Cross","R U2 R2 U' R2 U' R2 U2 R","Cross; two adjacent corners already correct."),
(23,"Headlights","Cross","R2 D R' U2 R D' R' U2 R'","Cross; headlights on the front, two corners solved."),
(24,"Chameleon","Cross","r U R' U' r' F R F'","Cross; one corner solved, looks like a chameleon."),
(25,"Bowtie","Cross","F' r U R' U' r' F R","Cross; bowtie shape."),
(26,"Antisune","Cross","R U2 R' U' R U' R'","Cross; three corners twisted counter-clockwise."),
(27,"Sune","Cross","R U R' U R U2 R'","Cross; three corners twisted clockwise."),
(28,"Stealth","Corners Oriented","r U R' U' r' R U R U' R'","All corners oriented; edges form a bar and a dot."),
(29,"Spotted Chameleon","Awkward","R U R' U' R U' R' F' U' F R U R'","Awkward shape with a bar on the left."),
(30,"Anti-Spotted Chameleon","Awkward","F R' F R2 U' R' U' R U R' F2","Awkward shape with a bar on the right."),
(31,"Couch","P Shape","R' U' F U R U' R' F' R","P shape facing left."),
(32,"Anti-Couch","P Shape","L U F' U' L' U L F L'","P shape facing right."),
(33,"Key","T Shape","R U R' U' R' F R F'","T shape; sexy move plus the F-trigger."),
(34,"Highway","C Shape","R U R2 U' R' F R U R U' F'","C shape with a dot in the middle."),
(35,"Fish Salad","Fish","R U2 R2 F R F' R U2 R'","Fish shape pointing up-left."),
(36,"Anti-Mounted Fish","W Shape","L' U' L U' L' U L U L F' L' F","W shape (wall) on the left."),
(37,"Mounted Fish","Fish","F R' F' R U R U' R'","Fish shape pointing up-right."),
(38,"Mario Bros","W Shape","R U R' U R U' R' U' R' F R F'","W shape (wall) on the right."),
(39,"Rice Cooker","Big Lightning","L F' L' U' L U F U' L'","Big lightning bolt on the left."),
(40,"Anti-Rice Cooker","Big Lightning","R' F R U R' U' F' U R","Big lightning bolt on the right."),
(41,"Awkward Fish","Awkward","R U R' U R U2 R' F R U R' U' F'","Awkward shape; Sune plus OLL 45."),
(42,"Anti-Awkward Fish","Awkward","R' U' R U' R' U2 R F R U R' U' F'","Awkward shape; Antisune plus OLL 45."),
(43,"Anti-Fung","P Shape","F' U' L' U L F","P shape facing back-left; inverse of OLL 44."),
(44,"Fung","P Shape","F U R U' R' F'","P shape facing front; one of the two easiest OLLs."),
(45,"Suit Up","T Shape","F R U R' U' F'","T shape; the other easiest OLL."),
(46,"Seein Headlights","C Shape","R' U' R' F R F' U R","C shape with headlights on the front."),
(47,"Breakneck","L Shape","R' U' R' F R F' R' F R F' U R","L shape; a double F-trigger."),
(48,"Right Back Squeezy","L Shape","F R U R' U' R U R' U' F'","L shape; two sexy moves inside F ... F'."),
(49,"Right Front Squeezy","L Shape","r U' r2 U r2 U r2 U' r","L shape; all r moves."),
(50,"Anti-Breakneck","L Shape","r' U r2 U' r2 U' r2 U r'","L shape; mirror of OLL 49."),
(51,"Bottlecap","I Shape","F U R U' R' U R U' R' F'","Line with two bars; F + double sexy + F'."),
(52,"Rail","I Shape","R U R' U R U' B U' B' R'","Line shape with a rail across the middle."),
(53,"Frying Pan","L Shape","r' U2 R U R' U' R U R' U r","L shape; a long r-move case."),
(54,"Anti-Frying Pan","L Shape","r U2 R' U' R U R' U' R U' r'","L shape; mirror of OLL 53."),
(55,"Highway Line","I Shape","R U2 R2 U' R U' R' U2 F R F'","Line with all four corners misoriented."),
(56,"Streetlights","I Shape","r U r' U R U' R' U R U' R' r U' r'","Line with headlights on both sides."),
(57,"Mummy","Corners Oriented","R U R' U' M' U R U' r'","All corners oriented; two opposite edges flipped."),
]
assert len(C)==57, len(C)
out = ['import type { CubeCase } from "./types";', '', 'export const OLL_CASES: CubeCase[] = [']
for n,name,group,alg,hint in C:
    out.append('  { id: "oll-%02d", label: "%d", name: "%s", group: "%s", hint: "%s",' % (n,n,name,group,hint))
    out.append('    algs: ["%s"] },' % alg)
out.append(']')
out.append('')
open("src/data/oll.ts","w",encoding="utf-8").write("\n".join(out))
print("oll.ts written:", len(C), "cases")
